[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "18"

# First, handle static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Then, handle all other routes through the SSR function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[functions]
  included_files = ["dist/**"]
