[build]
  command = "npm run build"
  publish = "dist"
  functions = "build"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
