[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
