[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  include = ["dist/**"]
  exclude = ["node_modules/**"]

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**"]

# First, handle static assets
[[redirects]]
  from = "/assets/*"
  to = "/dist/client/assets/:splat"
  status = 200
  force = true


# Then, handle all other routes through the SSR function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
